# Generated by Django 4.1.1 on 2022-11-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingMall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
