# Generated by Django 4.1.1 on 2022-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingMall', '0002_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
