# Generated by Django 4.1.1 on 2022-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingMall', '0003_alter_post_content_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
